In [2]:
%load_ext autoreload
%autoreload 2

In [7]:
import os

import numpy as np
import pandas as pd
import cvxpy as cp

from utils.setup_problem import Setup

In [8]:
data_dir_path = './inputs/winston2'

file_list = os.listdir(data_dir_path)

L_files = [filename.split('.csv')[0] for filename in file_list 
           if filename.startswith('L') and filename.endswith('.csv')]

U_files = [filename.split('.csv')[0] for filename in file_list 
           if filename.startswith('U') and filename.endswith('.csv')]

file_names_dict = {
    'supervised': L_files,
    'unsupervised': U_files,
    'rule': ['rules_2']
}



In [11]:
problem_instance = Setup(data_dir_path, file_names_dict)

In [12]:
objective, constraints = problem_instance.main(c1=10, c2=10)

Loading data ...
Done

Loading rules ...
Done

Identifying predicates ...
Done

Constructing objective function ...
Done

Constructing constraints ...
[['¬', Expression(AFFINE, UNKNOWN, ()), '⊕', Expression(AFFINE, UNKNOWN, ())], ['¬', Expression(AFFINE, UNKNOWN, ()), '⊕', Expression(AFFINE, UNKNOWN, ())], ['¬', Expression(AFFINE, UNKNOWN, ()), '⊕', Expression(AFFINE, UNKNOWN, ())], ['¬', Expression(AFFINE, UNKNOWN, ()), '⊕', Expression(AFFINE, UNKNOWN, ())], ['¬', Expression(AFFINE, UNKNOWN, ()), '¬', '⊗', '¬', Expression(AFFINE, UNKNOWN, ()), '⊕', Expression(AFFINE, UNKNOWN, ())], ['¬', Expression(AFFINE, UNKNOWN, ()), '¬', '⊗', '¬', Expression(AFFINE, UNKNOWN, ()), '¬', '⊗', '¬', Expression(AFFINE, UNKNOWN, ()), '¬', '⊗', '¬', Expression(AFFINE, UNKNOWN, ()), '⊕', Expression(AFFINE, UNKNOWN, ())], ['¬', Expression(AFFINE, UNKNOWN, ()), '¬', '⊗', '¬', Expression(AFFINE, UNKNOWN, ()), '⊕', Expression(AFFINE, UNKNOWN, ())], ['¬', Expression(AFFINE, UNKNOWN, ()), '¬', '⊗', '¬', Expressi

In [13]:
problem = cp.Problem(objective, constraints)
result = problem.solve(verbose=True)

                                     CVXPY                                     
                                     v1.3.2                                    
(CVXPY) Oct 22 04:49:56 PM: Your problem has 498 variables, 2190 constraints, and 0 parameters.
(CVXPY) Oct 22 04:49:56 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Oct 22 04:49:56 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Oct 22 04:49:56 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Oct 22 04:49:57 PM: Compiling problem (target solver=ECOS).
(CVXPY) Oct 22 04:49:57 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffin

In [20]:
x = np.random.rand(2, 3)
x

array([[0.27679277, 0.85011247, 0.58793345],
       [0.19755892, 0.77041254, 0.96021951]])

In [21]:
x1, x2 = x[0], x[1]
x1, x2

(array([0.27679277, 0.85011247, 0.58793345]),
 array([0.19755892, 0.77041254, 0.96021951]))

In [25]:
x1 @ x2

1.274165357297333