半定値対称行列の近似

https://www.sciencedirect.com/science/article/pii/0024379588902236

数値計算的に上手く行かないことがある

In [15]:
import numpy as np
from scipy.linalg import polar

def get_nearest_psd(A: np.ndarray) -> np.ndarray:
    
    B = .5 * (A.T + A)
    _, H = polar(B)
    return (B + H) / 2


def get_near_psd(A):
    C = (A + A.T)/2
    eigval, eigvec = np.linalg.eig(C)
    # eigval[eigval < 0] = 0
    eigval[eigval <= 0] = eigval.mean() * 1e-6

    return eigvec.dot(np.diag(eigval)).dot(eigvec.T)

In [2]:
"""
不定値な対称行列の生成
"""

shape = 10, 10

# ランダムな正方行列の生成
A = np.random.rand(shape[0], shape[1])

# ランダムで対角成分を0にする
mask = np.random.choice([True, False], size=A.shape, p=[0.5, 0.5])
A *= mask

# 対称行列にする
A = 0.5 * (A + A.T)

display(A)

# 固有値の計算
eigenvalues = np.linalg.eigvals(A)
print(eigenvalues)
print()

# 定値性のチェック
res = eigenvalues.min() >= 0 or eigenvalues.max() <= 0
print(f'Is this definite?: {res}')

array([[0.        , 0.21076861, 0.        , 0.29830813, 0.01276743,
        0.        , 0.11227109, 0.10573795, 0.76935881, 0.21493299],
       [0.21076861, 0.37872893, 0.        , 0.        , 0.13014657,
        0.        , 0.41802274, 0.63089818, 0.5390796 , 0.        ],
       [0.        , 0.        , 0.93704048, 0.02484609, 0.27448211,
        0.43794078, 0.54827998, 0.47377681, 0.        , 0.40752422],
       [0.29830813, 0.        , 0.02484609, 0.81073602, 0.30662622,
        0.        , 0.405218  , 0.        , 0.        , 0.28114274],
       [0.01276743, 0.13014657, 0.27448211, 0.30662622, 0.96028984,
        0.16956587, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.43794078, 0.        , 0.16956587,
        0.        , 0.28463763, 0.        , 0.63977204, 0.28439252],
       [0.11227109, 0.41802274, 0.54827998, 0.405218  , 0.        ,
        0.28463763, 0.        , 0.        , 0.17844899, 0.18239499],
       [0.10573795, 0.63089818, 0.4737768

[ 2.44985532  1.40097748 -0.8019448  -0.74767195 -0.32697515 -0.24430664
  0.0246724   1.04937725  0.79092477  0.62459274]

Is this definite?: False


In [3]:
""" 
不定値対称行列を半正定値対称行列で近似

上手く行っていないが原因は不明
"""

B = get_nearest_psd(A)
display(B)

# 固有値の計算
eigenvalues = np.linalg.eigvals(B)
print(eigenvalues)
print()

# 定値性のチェック
res = eigenvalues.min() >= 0 or eigenvalues.max() <= 0
print(f'Is this definite?: {res}')

array([[ 0.31976747,  0.23614047, -0.03346853,  0.2259664 ,  0.01257394,
         0.16450718,  0.13398861,  0.12803958,  0.55047083,  0.18620041],
       [ 0.23614047,  0.59258324,  0.10181174,  0.05080365,  0.08509429,
         0.06018924,  0.18133221,  0.46108997,  0.48721009,  0.03216106],
       [-0.03346853,  0.10181174,  1.07159783,  0.08068603,  0.24339981,
         0.3722805 ,  0.41832862,  0.30768783,  0.08382433,  0.31232192],
       [ 0.2259664 ,  0.05080365,  0.08068603,  0.87491065,  0.2784234 ,
         0.02529412,  0.30287577, -0.05324453,  0.04944221,  0.21675224],
       [ 0.01257394,  0.08509429,  0.24339981,  0.2784234 ,  0.97793387,
         0.13281173,  0.06763179,  0.03624175,  0.00425346,  0.03122408],
       [ 0.16450718,  0.06018924,  0.3722805 ,  0.02529412,  0.13281173,
         0.32942312,  0.1743503 ,  0.0890508 ,  0.42231723,  0.25548329],
       [ 0.13398861,  0.18133221,  0.41832862,  0.30287577,  0.06763179,
         0.1743503 ,  0.30649254,  0.18437722

[ 2.44985532e+00  1.40097748e+00  1.04937725e+00  7.90924768e-01
  6.24592742e-01  2.46723963e-02  6.48544597e-16 -4.75254529e-16
 -1.16029668e-16 -1.70273613e-16]

Is this definite?: False


In [16]:
""" 
不定値対称行列を半正定値対称行列で近似
"""

C = get_near_psd(A)
display(C)

# 固有値の計算
eigenvalues = np.linalg.eigvals(C)
print(eigenvalues)
print()

# 定値性のチェック
res = eigenvalues.min() >= 0 or eigenvalues.max() <= 0
print(f'Is this definite?: {res}')

array([[ 0.31976777,  0.23614048, -0.0334685 ,  0.22596632,  0.01257395,
         0.1645072 ,  0.13398867,  0.12803953,  0.5504707 ,  0.18620035],
       [ 0.23614048,  0.59258338,  0.10181178,  0.05080366,  0.08509427,
         0.06018925,  0.18133208,  0.46108987,  0.48721004,  0.03216114],
       [-0.0334685 ,  0.10181178,  1.07159792,  0.08068605,  0.2433998 ,
         0.37228045,  0.41832857,  0.30768772,  0.08382438,  0.31232184],
       [ 0.22596632,  0.05080366,  0.08068605,  0.87491072,  0.27842338,
         0.02529419,  0.3028757 , -0.05324452,  0.04944225,  0.21675218],
       [ 0.01257395,  0.08509427,  0.2433998 ,  0.27842338,  0.97793388,
         0.13281169,  0.06763183,  0.03624176,  0.00425346,  0.03122411],
       [ 0.1645072 ,  0.06018925,  0.37228045,  0.02529419,  0.13281169,
         0.32942338,  0.17435021,  0.08905091,  0.42231713,  0.25548323],
       [ 0.13398867,  0.18133208,  0.41832857,  0.3028757 ,  0.06763183,
         0.17435021,  0.30649272,  0.18437729

[2.44985532e+00 1.40097748e+00 1.04937725e+00 7.90924768e-01
 6.24592742e-01 2.46723963e-02 4.21950140e-07 4.21950141e-07
 4.21950140e-07 4.21950141e-07]

Is this definite?: True


In [17]:
abs(A - C).max(), abs(A - B).max(), abs(B - C).max()

(0.3294233831149184, 0.3294231222991535, 3.2843139935456733e-07)

In [18]:
abs(A - C).mean(), abs(A - B).mean(), abs(B - C).mean()

(0.08826816022090983, 0.08826810331295437, 6.151452228352234e-08)

In [19]:
A.mean(), B.mean(), C.mean()

(0.2255175567801451, 0.22828972392219365, 0.22828972553188154)