In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys

project_dir_path = '/Users/keisukeonoue/ws/lukasiewicz_1'
sys.path.append(project_dir_path)

import cvxpy as cp
import numpy as np
import pandas as pd 

from src.setup_problem_dual_single_task import Setup

from src.objective_function_single_task import ObjectiveFunction
from src.predicate import Predicate_dual

In [3]:
data_dir_path = os.path.join(project_dir_path, 'inputs/pima_indian_diabetes_3/')
train_data_dir_path = os.path.join(data_dir_path, "train")
file_list = os.listdir(train_data_dir_path)

L_files = [filename for filename in file_list 
           if filename.startswith('L') and filename.endswith('.csv')]

U_files = [filename for filename in file_list 
           if filename.startswith('U') and filename.endswith('.csv')]

file_names_dict = {
    'supervised': L_files,
    'unsupervised': U_files,
    'rule': ['rules_3.txt']
}

train_data_dir_path = os.path.join(data_dir_path, "train")

In [4]:
train_data_file_path = os.path.join(data_dir_path, "test/L_Outcome.csv")
train_data_file_path

'/Users/keisukeonoue/ws/lukasiewicz_1/inputs/pima_indian_diabetes_3/test/L_Outcome.csv'

In [13]:
problem_instance = Setup(
    train_data_dir_path, 
    file_names_dict, 
    ObjectiveFunction, 
    'Outcome', 
    c1=100, 
    c2=10
)

objective, constraints = problem_instance.main()
problem = cp.Problem(objective, constraints)
result = problem.solve(verbose=True)

load_data took 0.04875302314758301 seconds!
load_rules took 0.011752843856811523 seconds!
formulate_predicates_with_cvxpy took 8.606910705566406e-05 seconds!
shape of P: (1807, 1807)
finish l
finish h
finish s
finish l h
finish l s
finish h s
_construct_P_j took 1.0839200019836426 seconds!
construct_constraints took 0.0933678150177002 seconds!
                                     CVXPY                                     
                                     v1.3.2                                    
(CVXPY) Feb 02 03:36:53 PM: Your problem has 36756 variables, 1257 constraints, and 0 parameters.


/Users/keisukeonoue/ws/lukasiewicz_1/myenv/lib/python3.11/site-packages/cvxpy/problems/problem.py:157: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
/Users/keisukeonoue/ws/lukasiewicz_1/myenv/lib/python3.11/site-packages/cvxpy/problems/problem.py:163: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "


(CVXPY) Feb 02 03:36:53 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Feb 02 03:36:53 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Feb 02 03:36:53 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Feb 02 03:36:54 PM: Compiling problem (target solver=OSQP).
(CVXPY) Feb 02 03:36:54 PM: Reduction chain: FlipObjective -> CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> OSQP
(CVXPY) Feb 02 03:36:54 PM: Applying reduction FlipObjective
(CVXPY) Feb 02 03:36:54 PM: Applying reduction CvxAttr2Constr
(CVXPY) Feb 02 03:36:54 PM: Applying reduction Qp2SymbolicQp


/Users/keisukeonoue/ws/lukasiewicz_1/myenv/lib/python3.11/site-packages/cvxpy/problems/problem.py:163: UserWarning: Constraint #4 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "


(CVXPY) Feb 02 03:36:54 PM: Applying reduction QpMatrixStuffing


/Users/keisukeonoue/ws/lukasiewicz_1/myenv/lib/python3.11/site-packages/cvxpy/problems/problem.py:163: UserWarning: Constraint #5 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "


(CVXPY) Feb 02 03:36:59 PM: Applying reduction OSQP
(CVXPY) Feb 02 03:36:59 PM: Finished problem compilation (took 5.607e+00 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Feb 02 03:36:59 PM: Invoking solver OSQP  to obtain a solution.
-----------------------------------------------------------------
           OSQP v0.6.3  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2021
-----------------------------------------------------------------
problem:  variables n = 38563, constraints m = 39820
          nnz(P) + nnz(A) = 1092163
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.0

In [14]:
p_trained = Predicate_dual(
    problem_instance, 
    'Outcome', 
    opt_iter_num=100
)

[I 2024-02-02 15:37:06,135] A new study created in memory with name: no-name-7cb8d2a9-3c6b-4da3-9a4a-963117df9722
[I 2024-02-02 15:37:06,148] Trial 0 finished with value: 0.0 and parameters: {'b': -2.0599584550325094}. Best is trial 0 with value: 0.0.
[I 2024-02-02 15:37:06,160] Trial 1 finished with value: 0.49014084507042255 and parameters: {'b': 1.0469742681321552}. Best is trial 1 with value: 0.49014084507042255.
[I 2024-02-02 15:37:06,195] Trial 2 finished with value: 0.0 and parameters: {'b': -2.842114305492532}. Best is trial 1 with value: 0.49014084507042255.



min_bound: -3.0379200005446068
max_bound: 1.9620799994553935



[I 2024-02-02 15:37:06,209] Trial 3 finished with value: 0.49014084507042255 and parameters: {'b': 1.531871722373995}. Best is trial 1 with value: 0.49014084507042255.
[I 2024-02-02 15:37:06,257] Trial 4 finished with value: 0.0 and parameters: {'b': -2.5049926990289113}. Best is trial 1 with value: 0.49014084507042255.
[I 2024-02-02 15:37:06,275] Trial 5 finished with value: 0.6 and parameters: {'b': 0.3028434421772146}. Best is trial 5 with value: 0.6.
[I 2024-02-02 15:37:06,361] Trial 6 finished with value: 0.49014084507042255 and parameters: {'b': 0.6753844006576153}. Best is trial 5 with value: 0.6.
[I 2024-02-02 15:37:06,387] Trial 7 finished with value: 0.0 and parameters: {'b': -1.988467873115833}. Best is trial 5 with value: 0.6.
[I 2024-02-02 15:37:06,410] Trial 8 finished with value: 0.0 and parameters: {'b': -0.24668609906630445}. Best is trial 5 with value: 0.6.
[I 2024-02-02 15:37:06,424] Trial 9 finished with value: 0.49014084507042255 and parameters: {'b': 0.86603019942

In [15]:
p_trained.coeff

array([0.00996556, 0.08746423, 0.0659938 , 0.05620022, 0.06266074,
       0.06755724, 0.16267144, 0.32369764])

In [16]:
data = pd.read_csv(train_data_file_path, index_col=0)
X_test, y_test = data.drop(['target'], axis=1), data['target']

In [10]:
y_pred = p_trained(X_test)
y_pred

array([0.46785932, 0.658669  , 0.49450169, 0.44392991, 0.48052787,
       0.54267167, 0.51886198, 0.44814415, 0.47353835, 0.47179801,
       0.43183572, 0.52705426, 0.54992373, 0.4418774 , 0.50478772,
       0.4889475 , 0.56520235, 0.56244081, 0.47181709, 0.40668936,
       0.51955155, 0.43245868, 0.42172912, 0.51664866, 0.44544751,
       0.47113425, 0.49554917, 0.56016267, 0.4150638 , 0.56614094,
       0.56792038, 0.49132765, 0.61633114, 0.55475801, 0.55742353,
       0.47270124, 0.4308062 , 0.52074726, 0.59310177, 0.601718  ,
       0.5681635 , 0.66401367, 0.58121154, 0.4497453 , 0.49155976,
       0.66369387, 0.54578115, 0.54384851, 0.61984787, 0.58326161,
       0.49382717, 0.5190824 , 0.48588591, 0.59266427, 0.5449116 ,
       0.52225696, 0.51288728, 0.49195482, 0.5353671 , 0.54690472,
       0.47116794, 0.43704926, 0.51104565, 0.55642685, 0.55768255,
       0.62318222, 0.54565819, 0.48410711, 0.57809173, 0.45653944,
       0.51449   , 0.50328902, 0.45041228, 0.5610173 , 0.59422

In [17]:
y_pred_interpreted = np.where(y_pred >= 0.5, 1, -1)
y_pred_interpreted

array([-1,  1, -1, -1, -1,  1,  1, -1, -1, -1, -1,  1,  1, -1,  1, -1,  1,
        1, -1, -1,  1, -1, -1,  1, -1, -1, -1,  1, -1,  1,  1, -1,  1,  1,
        1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1,  1,  1,  1, -1,
        1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1,  1,  1,  1,  1,  1, -1,
        1, -1,  1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1,  1,
        1, -1,  1,  1,  1,  1,  1, -1, -1,  1, -1,  1,  1,  1, -1, -1,  1,
        1,  1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  1,  1, -1, -1, -1,  1,
       -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1])

In [18]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

from sklearn.metrics import confusion_matrix


acc = accuracy_score(y_test, y_pred_interpreted)
pre = precision_score(y_test, y_pred_interpreted)
rec = recall_score(y_test, y_pred_interpreted)
f1  = f1_score(y_test, y_pred_interpreted)
auc = roc_auc_score(y_test, y_pred_interpreted)

print(f'accuracy: {acc}')
print(f'precision: {pre}')
print(f'recall: {rec}')
print(f'f1: {f1}')
print(f'auc: {auc}')

accuracy: 0.7014925373134329
precision: 0.5256410256410257
recall: 0.9318181818181818
f1: 0.6721311475409836
auc: 0.7603535353535353
