In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 

In [27]:
data = pd.read_csv("./data/diabetes.csv")
display(data)

# データを特徴量とターゲットに分割
X = data.drop('Outcome', axis=1)
y = data['Outcome']

# 訓練データとテストデータに分割
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [29]:
X.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age  
count  768.000000                768.000000  768.000000  
mean    31.992578                  0.471876   33.240885  
std      7.884160                  0.331329   11.760232  
min      0.000000                  0.078000   21.000000  
25%     27.300000                  0.243750   24.000000  
50%     32.000000                  0.372500   29.000000  
75%     36.600000                  0.626250   41.000000  
max     67.100000                  2.420000   81.000000

In [30]:
# SVM（線形カーネル）のモデルを作成
svm_linear = SVC(kernel='linear')

# モデルを訓練
svm_linear.fit(X_train, y_train)

# テストデータで予測
y_pred_linear = svm_linear.predict(X_test)

# Accuracyを計算
accuracy_linear = accuracy_score(y_test, y_pred_linear)

# Confusion Matrixを計算
cm_linear = confusion_matrix(y_test, y_pred_linear)

# Classification Reportを出力
report_linear = classification_report(y_test, y_pred_linear)

# 結果を出力
print("SVM (Linear Kernel) Accuracy:", accuracy_linear)
print()
print()
print("SVM (Linear Kernel) Confusion Matrix:\n", cm_linear)
print()
print()
print("SVM (Linear Kernel) Classification Report:\n", report_linear)

SVM (Linear Kernel) Accuracy: 0.7532467532467533


SVM (Linear Kernel) Confusion Matrix:
 [[80 19]
 [19 36]]


SVM (Linear Kernel) Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.81      0.81        99
           1       0.65      0.65      0.65        55

    accuracy                           0.75       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.75      0.75      0.75       154



In [31]:
# SVM（RBFカーネル）のモデルを作成
svm_rbf = SVC(kernel='rbf')

# モデルを訓練
svm_rbf.fit(X_train, y_train)

# テストデータで予測
y_pred_rbf = svm_rbf.predict(X_test)

# Accuracyを計算
accuracy_rbf = accuracy_score(y_test, y_pred_rbf)

# Confusion Matrixを計算
cm_rbf = confusion_matrix(y_test, y_pred_rbf)

# Classification Reportを出力
report_rbf = classification_report(y_test, y_pred_rbf)

# 結果を出力
print("SVM (RBF Kernel) Accuracy:", accuracy_rbf)
print()
print()
print("SVM (RBF Kernel) Confusion Matrix:\n", cm_rbf)
print()
print()
print("SVM (RBF Kernel) Classification Report:\n", report_rbf)

SVM (RBF Kernel) Accuracy: 0.7662337662337663


SVM (RBF Kernel) Confusion Matrix:
 [[87 12]
 [24 31]]


SVM (RBF Kernel) Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.88      0.83        99
           1       0.72      0.56      0.63        55

    accuracy                           0.77       154
   macro avg       0.75      0.72      0.73       154
weighted avg       0.76      0.77      0.76       154



In [32]:
# ランダムフォレストのモデルを作成
rf = RandomForestClassifier()

# モデルを訓練
rf.fit(X_train, y_train)

# テストデータで予測
y_pred_rf = rf.predict(X_test)

# Accuracyを計算
accuracy_rf = accuracy_score(y_test, y_pred_rf)

# Confusion Matrixを計算
cm_rf = confusion_matrix(y_test, y_pred_rf)

# Classification Reportを出力
report_rf = classification_report(y_test, y_pred_rf)


# 結果を出力
print("Random Forest Accuracy:", accuracy_rf)
print()
print()
print("Random Forest Confusion Matrix:\n", cm_rf)
print()
print()
print("Random Forest Classification Report:\n", report_rf)

Random Forest Accuracy: 0.7597402597402597


Random Forest Confusion Matrix:
 [[81 18]
 [19 36]]


Random Forest Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.82      0.81        99
           1       0.67      0.65      0.66        55

    accuracy                           0.76       154
   macro avg       0.74      0.74      0.74       154
weighted avg       0.76      0.76      0.76       154



In [33]:
rf.n_estimators

100

# https://www.kaggle.com/code/iamyajat/eda-cleaning-modelling-on-diabetes-dataset#Evaluation

In [34]:
data = pd.read_csv("./data/diabetes.csv")
display(data)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [35]:
X.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age  
count  768.000000                768.000000  768.000000  
mean    31.992578                  0.471876   33.240885  
std      7.884160                  0.331329   11.760232  
min      0.000000                  0.078000   21.000000  
25%     27.300000                  0.243750   24.000000  
50%     32.000000                  0.372500   29.000000  
75%     36.600000                  0.626250   41.000000  
max     67.100000                  2.420000   81.000000

In [36]:
# 欠損値

data["Glucose"] = data["Glucose"].apply(lambda x: np.nan if x == 0 else x)  # Replace 0 values in Glucose column with NaN
data["BloodPressure"] = data["BloodPressure"].apply(lambda x: np.nan if x == 0 else x)  # Replace 0 values in BloodPressure column with NaN
data["SkinThickness"] = data["SkinThickness"].apply(lambda x: np.nan if x == 0 else x)  # Replace 0 values in SkinThickness column with NaN
data["Insulin"] = data["Insulin"].apply(lambda x: np.nan if x == 0 else x)  # Replace 0 values in Insulin column with NaN
data["BMI"] = data["BMI"].apply(lambda x: np.nan if x == 0 else x)  # Replace 0 values in BMI column with NaN

In [37]:
data.isnull().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [38]:
# Insulin は欠損率が高いので今回は除外する
data = data.drop(columns=['Insulin'])

In [39]:
# Highly skewed
data["BMI"].replace(to_replace=np.nan, value=data["BMI"].median(), inplace=True)
data["Pregnancies"].replace(to_replace=np.nan, value=data["Pregnancies"].median(), inplace=True)

# Normal
data["Glucose"].replace(to_replace=np.nan, value=data["Glucose"].mean(), inplace=True)
data["BloodPressure"].replace(to_replace=np.nan, value=data["BloodPressure"].mean(), inplace=True)
data["SkinThickness"].replace(to_replace=np.nan, value=data["SkinThickness"].mean(), inplace=True)


In [40]:
# 外れ値の除去

Q1 = data.quantile(0.25)
Q3 = data.quantile(0.75)
IQR = Q3 - Q1
print(IQR)
print()

data_out = data[~((data < (Q1 - 1.5 * IQR)) | (data > (Q3 + 1.5 * IQR))).any(axis=1)]
print(f'Before: {data.shape}, After: {data_out.shape}')


Pregnancies                  5.0000
Glucose                     40.5000
BloodPressure               16.0000
SkinThickness                7.0000
BMI                          9.1000
DiabetesPedigreeFunction     0.3825
Age                         17.0000
Outcome                      1.0000
dtype: float64

Before: (768, 8), After: (627, 8)


In [17]:
data

Pregnancies  Glucose  BloodPressure  SkinThickness   BMI  \
0              6    148.0           72.0       35.00000  33.6   
1              1     85.0           66.0       29.00000  26.6   
2              8    183.0           64.0       29.15342  23.3   
3              1     89.0           66.0       23.00000  28.1   
4              0    137.0           40.0       35.00000  43.1   
..           ...      ...            ...            ...   ...   
763           10    101.0           76.0       48.00000  32.9   
764            2    122.0           70.0       27.00000  36.8   
765            5    121.0           72.0       23.00000  26.2   
766            1    126.0           60.0       29.15342  30.1   
767            1     93.0           70.0       31.00000  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 8 columns]

In [41]:
data = data_out

In [42]:
from sklearn.preprocessing import MinMaxScaler

data = data_out

X = data[data.columns[:-1]]
y = data['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, stratify=y)

norm = MinMaxScaler().fit(X_train)
X_train_norm = norm.transform(X_train)
X_test_norm = norm.transform(X_test)

In [43]:
pd.DataFrame(X_train_norm, columns=X.columns)

Pregnancies   Glucose  BloodPressure  SkinThickness       BMI  \
0       0.384615  0.519481       0.500000       0.524201  0.503185   
1       0.615385  0.993506       0.500000       0.524201  0.245223   
2       0.000000  1.000000       0.366667       0.629630  0.735669   
3       0.384615  0.435065       0.466667       0.481481  0.181529   
4       1.000000  0.701299       0.766667       0.666667  0.273885   
..           ...       ...            ...            ...       ...   
496     0.153846  0.636364       0.633333       0.111111  0.207006   
497     0.307692  0.357143       0.466667       0.074074  0.235669   
498     0.076923  0.337662       0.333333       0.444444  0.477707   
499     0.692308  0.701299       0.566667       0.703704  0.509554   
500     0.307692  0.636364       0.700000       0.524201  0.821656   

     DiabetesPedigreeFunction       Age  
0                    0.127583  0.377778  
1                    1.000000  0.400000  
2                    0.380952  0.155556  
3                    0.295597  0.133333  
4                    0.586703  0.488889  
..                        ...       ...  
496                  0.613657  0.000000  
497                  0.194070  0.155556  
498                  0.189578  0.000000  
499                  0.732255  0.266667  
500                  0.509434  0.022222  

[501 rows x 7 columns]

In [44]:
pd.DataFrame(X_train_norm, columns=X.columns).describe()

Pregnancies     Glucose  BloodPressure  SkinThickness         BMI  \
count   501.000000  501.000000     501.000000     501.000000  501.000000   
mean      0.310763    0.505838       0.464309       0.506441    0.437666   
std       0.254410    0.198617       0.178408       0.226209    0.193907   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       0.076923    0.363636       0.333333       0.407407    0.296178   
50%       0.230769    0.474026       0.466667       0.524201    0.439490   
75%       0.461538    0.636364       0.566667       0.592593    0.557325   
max       1.000000    1.000000       1.000000       1.000000    1.000000   

       DiabetesPedigreeFunction         Age  
count                501.000000  501.000000  
mean                   0.304406    0.268574  
std                    0.220205    0.253519  
min                    0.000000    0.000000  
25%                    0.141959    0.066667  
50%                    0.235400    0.177778  
75%                    0.441150    0.422222  
max                    1.000000    1.000000

In [45]:
# ランダムフォレストのモデルを作成
rf = RandomForestClassifier()

# モデルを訓練
rf.fit(X_train_norm, y_train)

# テストデータで予測
y_pred_rf = rf.predict(X_test_norm)

# Accuracyを計算
accuracy_rf = accuracy_score(y_test, y_pred_rf)

# Confusion Matrixを計算
cm_rf = confusion_matrix(y_test, y_pred_rf)

# Classification Reportを出力
report_rf = classification_report(y_test, y_pred_rf)


# 結果を出力
print("Random Forest Accuracy:", accuracy_rf)
print()
print()
print("Random Forest Confusion Matrix:\n", cm_rf)
print()
print()
print("Random Forest Classification Report:\n", report_rf)

Random Forest Accuracy: 0.7619047619047619


Random Forest Confusion Matrix:
 [[70 13]
 [17 26]]


Random Forest Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.84      0.82        83
           1       0.67      0.60      0.63        43

    accuracy                           0.76       126
   macro avg       0.74      0.72      0.73       126
weighted avg       0.76      0.76      0.76       126



# さらに離散化してみる

In [22]:
bins = 3
labels = [0, 1, 2]

for column in range(X_train_norm.shape[1]):
    X_train_norm[:, column] = pd.cut(X_train_norm[:, column], bins=bins, labels=labels)
    X_test_norm[:, column] = pd.cut(X_test_norm[:, column], bins=bins, labels=labels)

In [23]:
display(pd.DataFrame(X_train_norm, columns=X.columns).head())

Pregnancies  Glucose  BloodPressure  SkinThickness  BMI  \
0          1.0      2.0            2.0            0.0  1.0   
1          0.0      0.0            1.0            0.0  0.0   
2          0.0      1.0            1.0            0.0  0.0   
3          0.0      1.0            1.0            0.0  0.0   
4          0.0      2.0            0.0            0.0  0.0   

   DiabetesPedigreeFunction  Age  
0                       0.0  1.0  
1                       0.0  0.0  
2                       1.0  0.0  
3                       0.0  0.0  
4                       0.0  0.0

In [24]:
# ランダムフォレストのモデルを作成
rf = RandomForestClassifier()

# モデルを訓練
rf.fit(X_train_norm, y_train)

# テストデータで予測
y_pred_rf = rf.predict(X_test_norm)

# Accuracyを計算
accuracy_rf = accuracy_score(y_test, y_pred_rf)

# Confusion Matrixを計算
cm_rf = confusion_matrix(y_test, y_pred_rf)

# Classification Reportを出力
report_rf = classification_report(y_test, y_pred_rf)


# 結果を出力
print("Random Forest Accuracy:", accuracy_rf)
print()
print()
print("Random Forest Confusion Matrix:\n", cm_rf)
print()
print()
print("Random Forest Classification Report:\n", report_rf)

Random Forest Accuracy: 0.7077922077922078


Random Forest Confusion Matrix:
 [[75 25]
 [20 34]]


Random Forest Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.75      0.77       100
           1       0.58      0.63      0.60        54

    accuracy                           0.71       154
   macro avg       0.68      0.69      0.69       154
weighted avg       0.71      0.71      0.71       154

